### PR TITLE
Add extension option so the output files can end in .css if needed

### PR DESCRIPTION
**Pull request by orestis**
Hi, would you be interested in pulling this in? Shadow-cljs expects the CSS files to end in .css for it to do auto-reloading, and in any case having .css files end in .scss was very confusing for me in the beginning. Thanks!

### CODE REVIEW

**Comment by Deraen** [comment]
Hmm, the extension should already be correct. I guess you tried the SNAPSNOT version?

Boot task replaces the extension: https://github.com/Deraen/sass4clj/blob/master/src/deraen/boot_sass.clj#L86 so I guess it is possible that I missed relevant piece when I build the api ns.

**Comment by Deraen** [comment]
Fixed by https://github.com/Deraen/sass4clj/commit/91bec0705254a990b1542114d25b50b9137d7f63 & new SNAPSHOT deployed

**Comment by Deraen** [comment]
Cause was that I copied parts of code from less4clj which has a bit different API and the output extension is set in different part.

**Comment by orestis** [comment]
Thanks! Yes, I was using the latest master for the api namespace.

**Pull request closed without merging**
